In this challenge we’ll create a Content View. Red Hat Satellite uses
Content Views to create customized repositories from the repositories.
You can use Content Views to define which software versions a particular
environment uses. For example, a Production environment might use a
Content View containing older package versions, while a Development
environment might use a Content View containing newer package versions.

Since this is a basic introduction to Satellite, we will only create a
Content View for the purpose of providing content to RHEL hosts, without
regard for Test, Production lifecycle use cases.

To learn more about Content Views and how to use them to manage content
for different lifecycle environments, please see
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/managing_content/managing_content_views_content-management[Managing
Content Views] in Satellite documentation.

Click on `+Content Views+`.

Click on `+Create New View+`.

We’ll name this content view `+RHEL9+`:

[source,bash]
----
RHEL9
----

Click `+Create content view+` to save it.

____
*NOTE:* Please ensure that you type `+RHEL9+` in capital letters. We’ll
need this value in step 6 of this lab.
____

Add the `+BaseOS+` and `+AppStream+` repos. Click `+Add Repositories+`.

Click `+Publish New Version+`.

Next we’ll complete the following steps to publish and promote the
content view.

[arabic]
. Click the sliding `+Promote+` button.
. Select the lifecycle environment you wish to promote the content view
to. In this case it is `+Test+`.
. Click `+Next+` to review the task.

Review the details and then click `+Finish+`.
